apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/frontend:v0.5.0
        name: frontend
        env:
        - name: PORT
          value: "8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: AD_SERVICE_ADDR
          value: "adservice:9555"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:5050"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice:8080"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080