apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkoutservice
  name: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.5.0
        name: checkoutservice
        env:
        - name: PORT
          value: "5050"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:50051"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
        - name: CART_SERVICE_ADDR
          value: "cartservice:7070"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:7000"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:8080"
        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice:50051"

---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  selector:
    app: checkoutservice
  ports:
  - port: 5050
    targetPort: 5050